PERSONAL_DATA_DISCLOSURE.md

Place a copy of the personal data disclosure form at the top level of the module github repository to disclose stored types of personal data
- added PERSONAL_DATA_DISCLOSURE.md file
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …

EDGDEMATIC-6 - Add personal data disclosure form

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/ed/client/interceptor/FeignRequestInterceptor.java
src/main/java/org/folio/ed/controller/UpdateAsrItemStatusAvailableController.java
src/main/java/org/folio/ed/service/RemoteStorageService.java
src/main/resources/swagger.api/edge-dematic.yaml
src/test/java/org/folio/ed/integration/EmsIntegrationTest.java
src/test/resources/mappings/users.json

Improving, refactoring, updating for [PR#4](https://github.com/folio-org/edge-dematic/pull/4).

EDGEDEMATIC-1 - Dematic EMS integration

---

Dockerfile
run.sh
src/main/java/org/folio/ed/client/EnrichHeadersClient.java
src/main/java/org/folio/ed/client/logger/SensitiveDataProtectionLogger.java
src/main/java/org/folio/ed/service/SecurityManagerService.java
src/main/resources/application.yml
src/test/resources/application-test.yml

[FOLIO-3014](https://issues.folio.org/browse/FOLIO-3014) - Add edge-dematic module to testing env/testing and snapshot VMs
Improving configuration for deploying edge-dematic on envs.

FOLIO-3014 - Add edge-dematic module to testing env/testing and snapshot VMs

---

pom.xml
src/main/java/org/folio/ed/error/ErrorControllerImpl.java
src/main/java/org/folio/ed/security/EdgeSecurityFilter.java
src/main/resources/application.yml
src/test/java/org/folio/ed/TestBase.java
src/test/java/org/folio/ed/TestSuite.java
src/test/java/org/folio/ed/integration/EmsIntegrationTest.java
src/test/java/org/folio/ed/security/EdgeSecurityFilterTest.java

[EDGDEMATIC-12](https://issues.folio.org/browse/EDGDEMATIC-12) - Health-check for edge-dematic
Health check status protocol for edge-dematic
Spring actuator enablement
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

EDGDEMATIC-12 - Health-check for edge-dematic

---

NEWS.md
pom.xml

EDGDEMATIC (edge-dematic) release https://issues.folio.org/browse/EDGDEMATIC-3
While it's …

EDGDEMATIC-3 - Release 1.0.0

---

src/main/java/org/folio/ed/service/SecurityManagerService.java
src/main/resources/application.yml

[EDGDEMATIC-16](https://issues.folio.org/browse/EDGDEMATIC-16) - Deployment issue: edge-dematic can't be configured for integration with AWS
Fixing issue with AWS integration for retrieving tenants/users
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …

EDGDEMATIC-16 - Deployment issue: edge-dematic can't be configured for integration with AWS

---

NEWS.md
pom.xml
src/main/java/org/folio/ed/service/SecurityManagerService.java
src/main/resources/application.yml

[EDGDEMATIC-17](https://issues.folio.org/browse/EDGDEMATIC-17) - Bugfix release 1.0.1

EDGDEMATIC-17 - Release-1.0.1

---

NEWS.md
README.md
pom.xml

[EDGDEMATIC-18](https://issues.folio.org/browse/EDGDEMATIC-18) - Bugfix release 1.0.2

EDGEDEMATIC-18 - Release 1.0.2

---

NEWS.md
README.md
src/main/java/org/folio/ed/security/TenantAwareAWSParamStore.java
src/main/java/org/folio/ed/service/SecurityManagerService.java
src/main/resources/ephemeral.properties
src/test/java/org/folio/ed/TestBase.java
src/test/java/org/folio/ed/security/SecurityManagerServiceTest.java
src/test/java/org/folio/ed/security/TenantAwareAWSParamStoreTest.java

[EDGDEMATIC-20](https://issues.folio.org/browse/EDGDEMATIC-20) - edge-dematic fails during deployment time
Fix AWS deployment issue for edge-dematic
Fix secured store logic.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

EDGDEMATIC-20 - edge-dematic fails during deployment time

---

NEWS.md
README.md
pom.xml
src/main/java/org/folio/ed/security/TenantAwareAWSParamStore.java
src/main/java/org/folio/ed/service/SecurityManagerService.java
src/main/resources/ephemeral.properties
src/test/java/org/folio/ed/TestBase.java
src/test/java/org/folio/ed/security/SecurityManagerServiceTest.java
src/test/java/org/folio/ed/security/TenantAwareAWSParamStoreTest.java

[EDGDEMATIC-23](https://issues.folio.org/browse/EDGDEMATIC-23) - Bugfix release 1.0.3

EDGDEMATIC-23 - Release 1.0.3

---

README.md
pom.xml
src/main/java/org/folio/ed/security/SecureTenantsProducer.java
src/main/java/org/folio/ed/security/TenantAwareAWSParamStore.java
src/main/java/org/folio/ed/service/SecurityManagerService.java
src/main/resources/application.yml
src/test/java/org/folio/ed/TestSuite.java
src/test/java/org/folio/ed/security/SecureTenantsProducerTest.java
src/test/java/org/folio/ed/security/TenantAwareAWSParamStoreTest.java

[EDGDEMATIC-19](https://issues.folio.org/browse/EDGDEMATIC-19) - Make deployment parameters configurable 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

EDGDEMATIC-19 - Make deployment parameters configurable

---

src/main/java/org/folio/ed/service/RemoteStorageService.java
src/test/resources/mappings/remote_storage.json

[EDGDEMATIC-28](https://issues.folio.org/browse/EDGDEMATIC-28) - edge-demotic doesn't update remote storage configurations for Dematic StagingDirector
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …

EDGDEMATIC-28 - edge-demotic doesn't update remote storage configurations for Dematic StagingDirector

---

NEWS.md
pom.xml
src/main/java/org/folio/ed/service/RemoteStorageService.java
src/test/resources/mappings/remote_storage.json

[EDGDEMATIC-29](https://issues.folio.org/browse/EDGDEMATIC-29) - Hotfix release 1.1.0

EDGDEMATIC-29 - Release 1.1.0

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

[EDGDEMATIC-13](https://issues.folio.org/browse/EDGDEMATIC-13) - Release 1.2.0

EDGDEMATIC-13 - Release 1.2.0

---

src/main/java/org/folio/ed/client/RemoteStorageClient.java
src/test/resources/mappings/remote_storage.json

[EDGDEMATIC-31](https://issues.folio.org/browse/EDGDEMATIC-31) - GET asrService/asr/lookupNewAsrItems doesn't retrieve new accession queue records
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …

EDGDEMATIC-31 - GET asrService/asr/lookupNewAsrItems doesn't retrieve new accession queue records

---

src/main/java/org/folio/ed/client/RemoteStorageClient.java
src/test/resources/mappings/remote_storage.json

Revert EDGDEMATIC-31

---

src/main/java/org/folio/ed/handler/FeedbackChannelHandler.java
src/main/java/org/folio/ed/handler/PrimaryChannelHandler.java
src/main/java/org/folio/ed/handler/StatusChannelHandler.java
src/main/java/org/folio/ed/service/RemoteStorageService.java
src/main/java/org/folio/ed/service/StagingDirectorIntegrationService.java
src/main/java/org/folio/ed/util/StagingDirectorMessageHelper.java
src/main/resources/application.yml
src/test/java/org/folio/ed/integration/StagingDirectorIntegrationTest.java
src/test/resources/application-test.yml

[EDGDEMATIC-33](https://issues.folio.org/browse/EDGDEMATIC-33) - Staging Director: TCP connection error
* fixed error
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

EDGDEMATIC-33 - Staging Director: TCP connection error

---

NEWS.md
pom.xml
src/main/java/org/folio/ed/handler/FeedbackChannelHandler.java
src/main/java/org/folio/ed/handler/PrimaryChannelHandler.java
src/main/java/org/folio/ed/handler/StatusChannelHandler.java
src/main/java/org/folio/ed/service/RemoteStorageService.java
src/main/java/org/folio/ed/service/StagingDirectorIntegrationService.java
src/main/java/org/folio/ed/util/StagingDirectorMessageHelper.java
src/main/resources/application.yml
src/test/java/org/folio/ed/integration/StagingDirectorIntegrationTest.java
src/test/resources/application-test.yml

[EDGDEMATIC-34](https://issues.folio.org/browse/EDGDEMATIC-34) - EDGDEMATIC (edge-dematic) hotfix release

EDGDEMATIC-34 - EDGDEMATIC (edge-dematic) hotfix release

---

src/main/java/org/folio/ed/handler/PrimaryChannelHandler.java
src/test/java/org/folio/ed/integration/StagingDirectorIntegrationTest.java

[EDGDEMATIC-39](https://issues.folio.org/browse/EDGDEMATIC-39) - Dematic StagingDirector should not have automatic check-in
Automatic check-in should be disabled on receiving Pick Request message
* Disabled automatic check-in
* Updated unit tests
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

EDGDEMATIC-39 - Dematic StagingDirector should not have automatic check-in

---

NEWS.md
pom.xml
src/main/java/org/folio/ed/handler/PrimaryChannelHandler.java
src/test/java/org/folio/ed/integration/StagingDirectorIntegrationTest.java

[EDGDEMATIC-40](https://issues.folio.org/browse/EDGDEMATIC-40) - EDGDEMATIC (edge-dematic) R1 hotfix #4 release

EDGDEMATIC-40 - EDGDEMATIC (edge-dematic) R1 hotfix #4 release

---

NEWS.md
pom.xml
src/main/java/org/folio/ed/handler/PrimaryChannelHandler.java
src/test/java/org/folio/ed/integration/StagingDirectorIntegrationTest.java

[EDGDEMATIC-41](https://issues.folio.org/browse/EDGDEMATIC-41) - R1 Hotfix -> R2 Bugfix - Dematic StagingDirector should not have automatic check-in

EDGDEMATIC-41 - R1 Hotfix -> R2 Bugfix - Dematic StagingDirector should not have automatic check-in

---

pom.xml

[EDGDEMATIC-47](https://issues.folio.org/browse/EDGDEMATIC-47) - Kiwi R3 2021 - Log4j vulnerability verification and correction

EDGDEMATIC-47 - Kiwi R3 2021 - Log4j vulnerability verification and correction

---

NEWS.md
pom.xml

[EDGDEMATIC-51](https://issues.folio.org/browse/EDGDEMATIC-51) - EDGDEMATIC (edge-dematic) Kiwi Bugfix release

EDGDEMATIC-51 - Release 1.3.1

---

NEWS.md
pom.xml

[EDGDEMATIC-50](https://issues.folio.org/browse/EDGDEMATIC-50) - EDGDEMATIC (edge-dematic) Juniper Hotfix release

EDGDEMATIC-50 - Release 1.2.3

---

pom.xml

[EDGDEMATIC-52](https://issues.folio.org/browse/EDGDEMATIC-52) - Kiwi R3 2021 - Log4j edge- modules 2.17.0 upgrade

EDGDEMATIC-52 - Kiwi R3 2021 - Log4j edge- modules 2.17.0 upgrade

---

NEWS.md
pom.xml

[EDGDEMATIC-53](https://issues.folio.org/browse/EDGDEMATIC-53) - Kiwi R3 2021 Log4j module release

EDGDEMATIC-53 - Release 1.3.2

---

NEWS.md
pom.xml

[EDGDEMATIC-55](https://issues.folio.org/browse/EDGDEMATIC-55) - Juniper R2 2021 Log4j module release

EDGDEMATIC-55 - Release 1.2.4

---

pom.xml
src/test/java/org/folio/ed/config/MockServerConfig.java
src/test/java/org/folio/ed/integration/StagingDirectorIntegrationTest.java
src/test/java/org/folio/ed/support/ServerMessageHelper.java

[EDGDEMATIC-58](https://issues.folio.org/browse/EDGDEMATIC-58) - edge-dematic: folio-spring-base v3 update
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

EDGDEMATIC-58 - edge-dematic: folio-spring-base v3 update

---

NEWS.md
pom.xml

[EDGDEMATIC-56](https://issues.folio.org/browse/EDGDEMATIC-56) - Release 1.5.0

EDGDEMATIC-56 - Release 1.5.0

---

pom.xml

[EDGDEMATIC-64](https://issues.folio.org/browse/EDGDEMATIC-64) - Spring4Shell Lotus (CVE-2022-22965)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …

EDGDEMATIC-64 - spring-boot-starter-parent v.2.6.6

---

NEWS.md
pom.xml

[EDGDEMATIC-65](https://issues.folio.org/browse/EDGDEMATIC-65) - EDGDEMATIC (edge-dematic) Lotus BF release
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

EDGDEMATIC-65 - Release 1.5.1

---

pom.xml
src/main/java/org/folio/ed/client/logger/SensitiveDataProtectionLogger.java
src/test/java/org/folio/ed/integration/EmsIntegrationTest.java
src/test/java/org/folio/ed/security/EdgeSecurityFilterTest.java
src/test/java/org/folio/ed/security/SecurityManagerServiceTest.java

[EDGDEMATIC-66](https://issues.folio.org/browse/EDGDEMATIC-66) - edge-dematic Spring 2.7 for Morning Glory R2 2022
Upgrade spring-boot-starter-parent from 2.6.6 to 2.7.*.
Upgrade spring-cloud-starter-bootstrap from 3.0.4 to the latest released version.
Upgrade spring-cloud-starter-openfeign from 2.2.1.RELEASE to the latest release version.
Reason: See https://issues.folio.org/browse/FOLREL-546
Performed updates
- Are the JIRAs …

EDGDEMATIC-66 - edge-dematic Spring 2.7 for Morning Glory R2 2022

---

NEWS.md
pom.xml

[EDGDEMATIC-59](https://issues.folio.org/browse/EDGDEMATIC-59) - Release 1.6.0

EDGEDEMATIC-59 - Release 1.6.0

---

src/main/java/org/folio/ed/client/logger/SensitiveDataProtectionLogger.java
src/main/java/org/folio/ed/util/MessageTypes.java
src/test/java/org/folio/ed/integration/StagingDirectorIntegrationTest.java

[EDGDEMATIC-73](https://issues.folio.org/browse/EDGDEMATIC-73) - Investigate message needed to connect Dematic EMS via TCP/IP
Request filled (RF) message should not be rejected but skipped instead.
* fixed message processing logic
* updated unit tests
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

EDGDEMATIC-73 - Investigate message needed to connect Dematic EMS via TCP/IP

---

pom.xml

[EDGDEMATIC-74](https://issues.folio.org/browse/EDGDEMATIC-74) - edge-dematic: spring upgrade
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …

EDGDEMATIC-74 - edge-dematic: spring upgrade

---

NEWS.md
pom.xml

[EDGDEMATIC-68](https://issues.folio.org/browse/EDGDEMATIC-68) - EDGDEMATIC (edge-dematic) Nolana release

EDGDEMATIC-68 - Release 1.7.0

---

pom.xml
src/main/java/org/folio/ed/util/MessageTypes.java
src/test/java/org/folio/ed/integration/StagingDirectorIntegrationTest.java

[EDGDEMATIC-81](https://issues.folio.org/browse/EDGDEMATIC-81) - Failed accessioning due to missing pick request - Dematic
When testing accessioning with U of Missouri, accessioning failed due to a missing pick request message
* Fixed message processing logic
* Updated unit tests
Ideally all of the PRs involved in breaking changes would be merged in the …

EDGDEMATIC-81 - Failed accessioning due to missing pick request - Dematic

---

PULL_REQUEST_TEMPLATE.md
pom.xml
src/main/resources/application.yml

EDGDEMATIC-77 (https://issues.folio.org/browse/EDGDEMATIC-77) 
Logging improvement - Configuration
1. Enable the /loggers endpoint in our application.yml file
2.  folio-spring-base version upgraded
3. "Check logging" added to PULL_REQUEST_TEMPLATE.md

[EDGDEMATIC-77]: logging improvement - configuration

---

src/main/java/org/folio/ed/service/RemoteStorageService.java
src/main/java/org/folio/ed/service/SecurityManagerService.java

EDGDEMATIC-61 (https://issues.folio.org/browse/EDGDEMATIC-61)
1. Logging improvement
1. debug and info log added

[EDGDEMATIC-61] logging improvement

---

.rancher-pipeline.yml
Dockerfile
Jenkinsfile
pom.xml
src/main/java/org/folio/ed/controller/LookupAsrRequestsController.java
src/main/java/org/folio/ed/controller/LookupNewAsrItemsController.java
src/main/java/org/folio/ed/controller/UpdateASRItemStatusAvailableController.java
src/main/java/org/folio/ed/controller/UpdateASRItemStatusBeingRetrievedController.java
src/main/java/org/folio/ed/domain/entity/RequestWithHeaders.java
src/main/java/org/folio/ed/error/ErrorControllerImpl.java
src/main/java/org/folio/ed/handler/BasicExceptionHandler.java
src/main/java/org/folio/ed/security/EdgeSecurityFilter.java
src/main/java/org/folio/ed/service/RemoteStorageService.java
src/main/java/org/folio/ed/service/SecurityManagerService.java
src/main/java/org/folio/ed/service/StagingDirectorIntegrationService.java
src/main/java/org/folio/ed/util/ApiKeyHelper.java
src/test/java/org/folio/ed/TestBase.java
src/test/java/org/folio/ed/support/ServerMessageHandler.java

https://issues.folio.org/browse/EDGDEMATIC-78
https://issues.folio.org/browse/EDGDEMATIC-79
- Update the module to Spring boot v3.0.0 and identify issues.
- Update the module to Java 17 and identify issues.
- https://wiki.folio.org/display/TC/JDK+17+and+Java+17
- Identify issues related to Java 17 update
- Identify issues related to Spring boot v3.0.0 update
- The module compiles without errors

[EDGDEMATIC-78,79]Update to Java 17 and Spring boot v3.0.0 and identify issues.

---

src/main/java/org/folio/ed/domain/entity/RequestWithHeaders.java
src/main/java/org/folio/ed/security/EdgeSecurityFilter.java

"If-None-Match" header was added in previous commit as a workaround for NullPointerException in the ServletWebRequest::matchRequestedETags method. Replace this by fixing RequestWithHeaders::getHeaders method not to return enumeration with null element in case of absent header.
Ideally all of the PRs involved in breaking changes would be merged in the same …

EDGEMATIC-79 replace adding "If-None-Match" header(workaround for NullPointerException) with fix in getHeaders implementation

---

pom.xml

https://issues.folio.org/browse/EDGDEMATIC-84
1. Folio spring base version updated to pass build.
1. pom.xml updated to pass build

[EDGDEMATIC-84] 1. upgrade pom

---

pom.xml

The purpose of the PR is to update the folio spring base version to 7.0.0
While it's helpful …

EDGDEMATIC-85 folio-spring-base version updated to 7.0.0

---

src/main/java/org/folio/ed/service/StagingDirectorIntegrationService.java
src/test/java/org/folio/ed/service/StagingDirectorIntegrationServiceTest.java

Resolves [EDGDEMATIC-88](https://issues.folio.org/browse/EDGDEMATIC-88)
The purpose is this PR is to start the module properly without any errors being raised. 
In post construct method createIntegrationFlows() we have some logic that's why the module is not getting started properly.
So, we have tried adding try-catch block around it. Now we can see the module is getting started.
- Do PRs …

EDGDEMATIC-88 Edge-dematic module not started properly.

---

NEWS.md
pom.xml
src/main/java/org/folio/ed/service/StagingDirectorIntegrationService.java
src/test/java/org/folio/ed/service/StagingDirectorIntegrationServiceTest.java

https://issues.folio.org/browse/EDGDEMATIC-90

---

pom.xml

Updated the snapshot version in pom

[EDGDEMATIC-90] - Update the snapshot version in pom.xml

---

pom.xml

Upgrade to Spring Boot 3.1 and folio-spring-support 7.2
Updated the version in pom.xml
While …

[EDGDEMATIC-94] - Upgrade to Spring Boot 3.1 and folio-spring-support 7.2

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Poppy release
While it's helpful for reviewers to help identify potential problems, ensuring …

EDGEDEMATC-93 - Poppy Release

---

NEWS.md
pom.xml

To release 2.1.1
While it's helpful for reviewers to help identify potential problems, …

EDGDEMATIC-96 To release  2.1.1

---

NEWS.md
pom.xml

Increment pom version

---

pom.xml
src/main/resources/application.yml
src/test/java/org/folio/ed/config/MockServerConfig.java
src/test/java/org/folio/ed/integration/EmsIntegrationTest.java

Upgrade the versions for Q release.
While it's helpful for reviewers to help identify …

EDGDEMATIC-97 - Upgrade versions in pom for Q release.

---

pom.xml

[EDGDEMATIC-102] - Update pom version post release in master.

---

NEWS.md
pom.xml
src/main/java/org/folio/ed/EdgeDematicApplication.java

Tmp release 2.2.2

---

NEWS.md
pom.xml

Release 2.2.3
While it's helpful for reviewers to help identify potential problems, ensuring …

To release 2.2.3

---

src/main/java/org/folio/ed/handler/FeedbackChannelHandler.java
src/main/java/org/folio/ed/util/StagingDirectorErrorCodes.java
src/test/java/org/folio/ed/integration/StagingDirectorIntegrationTest.java

To fix the issue reported in EDGDEMATIC-108
The approach taken is to add extra error code in the enum and then return a TR message with code 000 and print error message in the logs. No further server invocation call will happen in other words the message will be just acknowledged.
(Received SM with ITEM MISSING ERROR CODE 004)
Ideally all of the PRs …

EDGDEMATIC-108 - Received SM with ITEM MISSING ERROR CODE 004

---

NEWS.md
pom.xml
src/main/java/org/folio/ed/handler/FeedbackChannelHandler.java
src/main/java/org/folio/ed/handler/StatusChannelHandler.java
src/main/java/org/folio/ed/util/StagingDirectorErrorCodes.java
src/test/java/org/folio/ed/integration/StagingDirectorIntegrationTest.java

To release 2.2.4

---

pom.xml
src/main/java/org/folio/ed/service/DematicSecurityManagerService.java

https://folio-org.atlassian.net/browse/EDGDEMATIC-114
While it's helpful for reviewers to …

EDGDEMATIC-114: upgraded folio-spring-base.version from 8.1.2 to 8.2.0

---

NEWS.md
pom.xml

To release 2.3.1

---

NEWS.md
pom.xml

Post release 2.3.1

---

pom.xml
src/main/java/org/folio/ed/security/TenantAwareAWSParamStore.java
src/test/java/org/folio/ed/security/TenantAwareAWSParamStoreTest.java

https://folio-org.atlassian.net/browse/EDGDEMATIC-118
While it's helpful for reviewers to …

EDGDEMATIC-118: upgraded edge-common.version

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/EDGDEMATIC-122
While it's helpful for reviewers to …

Sunflower release 2.4.0

---

pom.xml

Fix master branch from 2.4.1-SNAPSHOT to 2.5.0-SNAPSHOT

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/EDGDEMATIC-124
https://folio-org.atlassian.net/browse/EDGDEMATIC-126
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

To release 2.4.1

---

src/main/resources/application.yml

…compatible target type
https://folio-org.atlassian.net/browse/EDGDEMATIC-130
While it's …

EDGDEMATIC-130: fixed 'management.endpoint.loggers.access' uses an incompatible target type

---

NEWS.md
pom.xml
src/main/resources/application.yml

Sunflower Bug fix R1 2025
https://folio-org.atlassian.net/browse/EDGDEMATIC-129
While it's …

Sunflower release 2.4.2

---

.github/dependabot.yml
CODEOWNERS
PULL_REQUEST_TEMPLATE.md

- to have in place the process for automation of the updates of dependent modules
- to have standardized approach for all the Pull Requests created for the modules of volaris team
- for codeowners been automatically tagged in PRs
- add `dependabot.yml` config file
- update `PULL_REQUEST_TEMPLATE.md` file
- add `CODEOWNERS` file
[EDGEDEMATIC-132](https://folio-org.atlassian.net/browse/EDGDEMATIC-132)
- Are the JIRAs under active …

EDGEDEMATIC-132: Add config file for dependabot and template for pull request
